### ISSUE TITLE
Support hyperlinks from Integrations

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/openmetadata-site#16]
Add hyperlinks for each of the integrations so users can click and go to their respective connector settings and/or technology homepages.

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/5906984/154862033-9358ffd0-29cb-4a9a-96b1-a687785c3cac.png">

**Comment by mithmatt** [comment]
cc: @harshach @shahsank3t

**Comment by harshach** [comment]
done
