### ISSUE TITLE
Add testimonials section on home page

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/openmetadata-site#36]
This issue is to track adding a testimonials section on the home page, UI should look something like this.
![image](https://user-images.githubusercontent.com/59080942/173004060-79d31b9c-b6bb-4ad6-bfb1-91a141f2e36c.png)
cc: @devyani-kaushik 

@ShilpaVernekar, Please provide testimonials content for the same.
cc : @harshach @mesmith027 @shahsank3t

**Comment by ShilpaVernekar** [comment]
Thanks for creating this @Sachin-chaurasiya .... I was thinking about the same in the meeting today morning :)
Here's the doc for [testimonials](https://docs.google.com/document/d/1elN7XfcUszBixZU4EQaIdSYRjqvdxDynwkpZ_Ox_N-A/edit#heading=h.n4if3ruqzuoo)
I'll update here once I add the new ones

**Comment by Ashish8689** [comment]
https://github.com/open-metadata/openmetadata-site/pull/49
